version: '3.4'

services:
 postgres:
  container_name: postgres
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: pet_family
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  ports:
   - 5434:5432
  volumes:
   - postgres-data:/var/lib/postgresql/data
 petfamily.api:
    image: ${DOCKER_REGISTRY-}petfamilyapi
    build:
      context: .
      dockerfile: PetFamily.API/Dockerfile

volumes:
   postgres-data:
   